Repository silvadaniele/covoitsite, pull requests merged in 2019-02, with the labels that each got.

#9 use I18n translations and fix bugs
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/callbacks.coffee
  app/assets/stylesheets/application.scss
  app/controllers/account/rides_controller.rb
  app/controllers/application_controller.rb
  app/views/account/rides/_form.html.erb
  app/views/account/rides/edit.html.erb
  app/views/account/rides/index.html.erb
  app/views/account/rides/new.html.erb
  app/views/account/rides/show.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/rides/index.html.erb
  app/views/rides/show.html.erb
  config/application.rb
  config/locales/fr.yml
Labels: bug, chore, enhancement

#11 user name and validation
  Gemfile
  Gemfile.lock
  app/controllers/user/registrations_controller.rb
  app/models/ride.rb
  app/models/user.rb
  app/views/account/rides/_form.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/rides/index.html.erb
  app/views/rides/show.html.erb
  config/locales/fr.yml
  config/routes.rb
Labels: enhancement

#16 add mailer and procfile config
  Gemfile
  Gemfile.lock
  Procfile
  config/environments/development.rb
  config/environments/production.rb
Labels: chore

#18 add rollbar
  Gemfile
  Gemfile.lock
  config/initializers/rollbar.rb
Labels: chore

#19 Feature/request
  app/assets/javascripts/rides/requests.coffee
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/rides.scss
  app/assets/stylesheets/rides/requests.scss
  app/controllers/account/rides_controller.rb
  app/controllers/rides/requests_controller.rb
  app/controllers/rides_controller.rb
  app/helpers/rides/requests_helper.rb
  app/mailers/application_mailer.rb
  app/models/request.rb
  app/models/user.rb
  app/views/application_mailer/new_request.html.erb
  app/views/layouts/application.html.erb
  app/views/rides/contact.html.erb
  app/views/rides/index.html.erb
  app/views/rides/show.html.erb
  config/environments/development.rb
  config/routes.rb
  db/migrate/20190207165055_create_requests.rb
  db/schema.rb
  spec/mailers/previews/application_mailer_preview.rb
  test/controllers/.keep
  test/controllers/callbacks_controller_test.rb
  test/controllers/rides_controller_test.rb
  test/fixtures/requests.yml
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/ride_test.rb
  test/models/user_test.rb
Labels: feature

#20 Translation
  app/controllers/rides/requests_controller.rb
  app/models/request.rb
  app/views/application_mailer/new_request.html.erb
  app/views/rides/contact.html.erb
  app/views/rides/show.html.erb
  config/locales/fr.yml
  config/locales/pt-BR.yml
Labels: chore

#23 Language Selection
  app/controllers/application_controller.rb
  app/views/layouts/_navbar.html.erb
Labels: enhancement, feature
